apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: allow-create-rolebindings
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["rolebindings"]
  verbs: ["create"]
