apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - main
jobs:
  Checkout:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

  Build:
    needs: Checkout
    steps:
      - name: Configure git
        uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace
      - name: Checkout
        uses: cloudbees-io/checkout@v1
        
      - name: Build 
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          mvn clean install 

  UnitTest:
    needs: Build
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Build 
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          mvn test

      - name: Build12 
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          ls -l /cloudbees/workspace/target/surefire-reports
          cat /cloudbees/workspace/target/surefire-reports/*.txt