apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - main
jobs:
  Checkout:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

  Build:
    needs: Checkout
    steps:
      - name: Configure git
        uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace
      - name: Checkout
        uses: cloudbees-io/checkout@v1
        
      - name: Get Commit Information
        uses: docker://alpine/git:latest
        run: |
           echo "Commit ID: $(git rev-parse HEAD)" > /cloudbees/workspace/commit-info.txt
           echo "Commit Message: $(git log -1 --pretty=format:%s)" >> /cloudbees/workspace/commit-info.txt

      - name: Build
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          mvn clean install 
          ls -lR /cloudbees/workspace
          cat commit-info.txt

  UnitTest:
    needs: Build
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Run Unit Tests
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          mvn test
          ls -lR /cloudbees/workspace
        

  StaticAnalysis:
    steps:
      - uses: cloudbees-io/sonarqube-sast-scan-code@v1
        name: Scan
        kind: scan
        with:
          server-url: https://sonarqube.cb-demos.io
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          language: Java
      - uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v2
        name: Scan with Java
        kind: scan
        with:
          language: JAVA
      - uses: cloudbees-io/findsecbugs-sast-scan-code@v1
        name: Scan with Find Security Bugs
        kind: scan
        with:
          language: LANGUAGE_JAVA
      - uses: sbatchelder-cba/sonarqube-cba@v0.0.3
        name: Scan GP
        with:
          project-key: config-server
          token: ${{ secrets.token }}

  
  
  

  Evidence:
    needs: UnitTest
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
        
      - name: Get Commit Information
        uses: docker://alpine/git:latest
        run: |
           echo "Commit ID: $(git rev-parse HEAD)" > /cloudbees/workspace/commit-info.txt
           echo "Commit Message: $(git log -1 --pretty=format:%s)" >> /cloudbees/workspace/commit-info.txt

      - name: Publish test results
        uses: cloudbees-io/publish-test-results@v1
        with:
          test-type: JUnit
          folder-name: src/test
         
      - uses: cloudbees-io/publish-evidence-item@v1
        name: Publish workflow evidence
        with:
          content: |-
            # Sample Evidence output
            - Workflow ID: ${{ cloudbees.run_id }}
            - Commit Information:
              ```
              $(cat /cloudbees/workspace/commit-info.txt)
              ```

