apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - main
jobs:
  Checkout:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1
  Build:
    needs: Checkout
    steps:
      - uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace
      - name: checkout
        uses: cloudbees-io/checkout@v1
      - name: Build
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          mvn clean install -DskipTests=true
          ls

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .  # Specify the build context directory
          file: /cloudbees/workspace/Dockerfile 
          push: false  # Set to true to push the image to a registry
          tags: |
            configserver:latest  
          