apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - main
jobs:
  Checkout:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1

  Build:
    needs: Checkout
    steps:
      - uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace

      - name: checkout
        uses: cloudbees-io/checkout@v1

      - name: Build
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          mvn clean install -DskipTests=true
   
  NextStage:
    needs: Build
    steps:
      - name: Install Docker CLI
        uses: docker://docker:20.10.9
        run: |
          apk add --no-cache docker-cli
          apk add --no-cache iptables
          dockerd \
            --iptables=false \
            --ip-masq=false \
            --bridge=none \
            &
          sleep 10
          docker ps -a 

      - uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace

      - name: checkout
        uses: cloudbees-io/checkout@v1

      - name: Build
        uses: docker://docker:20.10.9
        run: |
          docker build -t configsample:3.2.4 .