apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - main
jobs:
  Checkout:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Fetch commit-info.md content
        uses: docker://alpine/git:latest
        id: fetch_content
        run: |
          apk add --no-cache curl
          content=$(curl -s https://raw.githubusercontent.com/cashokannamalai/spring-petclinic-config-server/main/commit-info.md)
          if [ -n "$content" ]; then
            echo "$content" > commit-info.txt
          else
            echo "Failed to fetch content."
            exit 1
          fi

      - name: Print System Property
        uses: docker://alpine/git:latest
        run: |
          if [ -f commit-info.txt ]; then
            content=$(cat commit-info.txt)
            echo "var.commid=${content}"
          else
            echo "commit-info.txt not found."
            exit 1
          fi

      - name: Publish workflow evidence item
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |-
              ## Test markup and property rendering
              - Run ID: ${{ cloudbees.run_id }}
              - Commit Info: ${{ steps.fetch_content.outputs.content }}
              - [backend.tar](https://ourcompany.com/repo/backend.tar)
