apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - main
jobs:
  Checkout:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1

  Build:
    needs: Checkout
   
    steps:
      
      - uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace

      - name: checkout
        uses: cloudbees-io/checkout@v1
      - name: Build
        uses: docker://maven:3-eclipse-temurin-17
        run: |
            mvn clean install -DskipTests=true

      - id: dockerconfig
        name: Configure container registry credentials
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: ${{ secrets.STAGING_DOCKER_REGISTRY }}
          username: ${{ secrets.STAGING_DOCKER_USERNAME }}
          password: ${{ secrets.STAGING_DOCKER_PASSWORD }}


      - name: Push image to OCI registry
        uses: cloudbees-io/kaniko@v1
        with:
         dockerfile: Dockerfile
         context: .
         destination: ${{ secrets.STAGING_DOCKER_REGISTRY }}/${{ secrets.STAGING_DOCKER_USERNAME }}/configserver:3.2.4
         build-args: docker images


  Deploy:
    needs: Build
    steps:
      - name: Validate GCP Service Account Key JSON
        uses: docker://my-org/validate-gcp-key-action:latest
        with:
          key: ${{ secrets.GCP_SA_KEY_JSON }}

      - name: Set up Google Cloud SDK
        uses: docker://google/cloud-sdk:latest
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY_JSON }}
        run: |
          echo "${GCP_SA_KEY}" > /tmp/gcp-key.json
          gcloud auth activate-service-account --key-file /tmp/gcp-key.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_CLUSTER_LOCATION }}