apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - main
jobs:
  Checkout:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1
  Build:
    needs: Checkout
    steps:
      - uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace
      - name: checkout
        uses: cloudbees-io/checkout@v1
      - name: Build
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          mvn clean install -DskipTests=true
 
      - uses: cloudbees-io/configure-oci-credentials@v1
        name: Login
        with:
          registry: nexus.preview.cb-demos.io/repository/petclinicimage/
          username: admin
          password: QPn^Y9QY%Q$gX^s$n%6$J

      - name: View Docker Config
        uses: cloudbees-io/kaniko@v1
        run: cat ~/.docker/config.json
  
      - uses: cloudbees-io/kaniko@v1
        name: dockerpush
        with:
          dockerfile: Dockerfile
          context: /cloudbees/workspace
          destination: ~/.docker/config.json
          build-args: docker build -t configserver:3.2.4
          labels: ashok
