apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - main
jobs:
  Checkout:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1

  Build:
    needs: Checkout
    steps:
      - uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace

      - name: checkout
        uses: cloudbees-io/checkout@v1

      - name: Build
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          mvn clean install -DskipTests=true

          


     
  NextStage:
    needs: Build
    steps:
      - name: Install and Start Docker
        uses: docker://docker:23.0.1-dind
        run: |
          apk add --no-cache docker-cli
          dockerd &

      - name: Build Docker Image
        uses: docker://docker:latest
        run: |
          chmod -R 777 /var/run/docker.sock
          docker build -t myapp:latest .
          
          
         
          
          

      

      
          