apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - main
jobs:
  Evidence:
   steps:
    - name: Checkout
      uses: cloudbees-io/checkout@v1

    - name: Fetch Commit Info
      id: fetch-commit-info
      uses: docker://alpine:latest
      run: |
        apk add --no-cache curl
        curl -o commit-info.md \
          https://github.com/cashokannamalai/spring-petclinic-config-server/raw/main/commit-info.md

  
        cat commit-info.md
