apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My Automation Workflow
on:
  push:
    branches:
      - main

jobs:
  Checkout:
    steps:
      - name: Checkout code
        uses: cloudbees-io/checkout@v1

  Build:
    needs: Checkout
    steps:
      - name: Set Docker Daemon permissions
        uses: docker://alpine:latest
        run: sudo chmod 666 /var/run/docker.sock  

      - name: Build with Maven
        uses: docker://maven:3-eclipse-temurin-17
        run: mvn clean install -DskipTests=true

  StaticAnalysis:
    needs: Build
    steps:
      - name: SonarQube Analysis
        uses: cloudbees-io/sonarqube-sast-scan-code@v1
        with:
          server-url: https://sonarqube.cb-demos.io
          username: ${{ secrets.SONAR_USERNAME }}
          password: ${{ secrets.SONAR_PASSWORD }}
          language: Java

      - name: Find Security Bugs Scan
        uses: cloudbees-io/findsecbugs-sast-scan-code@v1
        with:
          language: JAVA

  ArtifactPublish:
    needs: StaticAnalysis
    steps:
      - name: Publish to Nexus Repository
        uses: docker://maven:3-eclipse-temurin-17
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: mvn deploy -DskipTests -DaltDeploymentRepository=nexus::default::https://${NEXUS_USERNAME}:${NEXUS_PASSWORD}@nexus.preview.cb-demos.io/repository/Petclinic/

  DockerBuild:
    needs: ArtifactPublish
    steps:
      - name: Checkout code
        uses: cloudbees-io/checkout@v1

      - name: Docker Build
        uses: docker://docker:latest
        run: docker build -t config-server:3.2.4 .
