apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - main
jobs:
  Checkout:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Fetch commit-info.md content
        uses: docker://alpine:latest
        shell: sh
        id: fetch_content
        run: |
          apk add --no-cache curl
          curl -s -o commit-info.md https://raw.githubusercontent.com/cashokannamalai/spring-petclinic-config-server/main/commit-info.md || (echo "Failed to fetch commit-info.md" && exit 1)
          if [ ! -s commit-info.md ]; then
            echo "Error: commit-info.md is empty or could not be fetched."
            exit 1
          fi
          content=$(cat commit-info.md)
          echo "::set-output name=content::$content"

      - name: Publish evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |
            - Workflow ID: ${{ cloudbees.run_id }}
            - URL: https://github.com/cashokannamalai/spring-petclinic-config-server/blob/main/commit-info.md
            - File Content: |
              ${{ steps.fetch_content.outputs.content }}
