apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - main
jobs:
  Checkout:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

  Build:
    needs: Checkout
    steps:
      - name: Configure git
        uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace
          
      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Get Commit ID and Message
        id: get_commit_info
        uses: docker://alpine/git:latest
        run: |
          COMMIT_ID=$(git rev-parse HEAD)
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Commit ID: ${COMMIT_ID}" > commit_id.txt
          echo "Commit Message: ${COMMIT_MSG}" > commit_msg.txt
          echo "::set-output name=CommitId::${COMMIT_ID}"
          echo "::set-output name=CommitMsg::${COMMIT_MSG}"

      - name: Build
        uses: docker://maven:3-eclipse-temurin-17
        id: build
        run: |
          mvn clean install

      - name: Publish Evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |
            - Workflow ID: ${{ cloudbees.run_id }}
            - URL: ${{ cloudbees.api.url }}
            - Commit ID: ${{ steps.get_commit_info.outputs.CommitId }}
            - Commit Message: ${{ steps.get_commit_info.outputs.CommitMsg }}
