apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - main
jobs:
  Checkout:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1
  
  Build:
    needs: Checkout
    steps:
      - uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace
      - name: checkout
        uses: cloudbees-io/checkout@v1
      - name: Build
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          mvn clean install -DskipTests=true

  CheckDockerVersion:
    needs: Build
    steps:
      - name: Check Docker Version
        uses: docker://docker:23.0.1
        run: |
          docker version

  RootStage:
    needs: CheckDockerVersion
    steps:
      - name: Run as Root
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          whoami
          # Add your root user commands here
        user: root