apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - main
jobs:
  Checkout:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1

  Build:
    needs: Checkout
    steps:
      - uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace

      - name: checkout
        uses: cloudbees-io/checkout@v1

      - name: Build
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          mvn clean install -DskipTests=true

  
  DockerBuild:
    needs: Build
    steps:
      - name: Install Docker
        uses: docker://docker:23.0.1
        run: |
          apk update
          apk add --no-cache docker-cli
      - name: Docker Build
        uses: docker://docker:23.0.1
        run: |
          docker build -t config:3.2.4 .
      

