apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - main
jobs:
  Checkout:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

  Build:
    needs: Checkout
    steps:
      - name: Configure git
        uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace

      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Build
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          mvn clean install 
          git log -1 --pretty=format:"%H - %s" > /cloudbees/workspace/commit-info.txt
      - name: Capture Commit Info
        id: commit_info
        uses: docker://alpine:latest
        run: |
          cat /cloudbees/workspace/commit-info.txt

  UnitTest:
    needs: Build
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Run Unit Tests
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          mvn test
          ls -lR /cloudbees/workspace
          mvn surefire-report:report

  StaticAnalysis:
    steps:
      - uses: cloudbees-io/sonarqube-sast-scan-code@v1
        name: SonarQube Scan
        kind: scan
        with:
          server-url: https://sonarqube.cb-demos.io
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          language: Java
      - name: Capture Code Coverage and Violations
        uses: docker://alpine:latest
        run: |
          curl -u ${{ secrets.username }}:${{ secrets.password }} "https://sonarqube.cb-demos.io/api/measures/component?componentKey=myproject&metricKeys=coverage,violations,critical_violations" > /cloudbees/workspace/sonar-results.json

  ArtifactPublish:
    needs: UnitTest
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Publish to Nexus
        uses: docker://maven:3-eclipse-temurin-17
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: |
          mvn deploy \
            -DaltDeploymentRepository=nexus::default::https://${NEXUS_USERNAME}:${NEXUS_PASSWORD}@nexus.preview.cb-demos.io/repository/Petclinic/

  DockerImageBuildAndPush:
    needs: ArtifactPublish
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      - name: Build Docker Image
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          mvn clean install -DskipTests=true
      - name: Configure container registry credentials
        id: dockerconfig
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: ${{ secrets.STAGING_DOCKER_REGISTRY }}
          username: ${{ secrets.STAGING_DOCKER_USERNAME }}
          password: ${{ secrets.STAGING_DOCKER_PASSWORD }}

      - name: Push image to OCI registry
        uses: cloudbees-io/kaniko@v1
        with:
          dockerfile: Dockerfile
          context: .
          destination: ${{ secrets.STAGING_DOCKER_REGISTRY }}/${{ secrets.STAGING_DOCKER_USERNAME }}/configserver:3.2.4

  Approval:
    needs: DockerImageBuildAndPush
    type: manual-approval
    environment: ashok
    steps:
      - name: Approval
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          echo "Manual approval required before proceeding to deployment."

  DeployInGKE:
    needs: Approval
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
        
      - uses: cashokannamalai/kubeconfig@v1
        name: Set kubeconfig
        with:
          secname: ${{ secrets.kubeconfig }}
      - uses: docker://bitnami/kubectl:latest
        name: Deploy image
        shell: sh
        run: |
          kubectl apply -f /cloudbees/workspace/deployment-service.yaml

  Evidence:
    needs: DeployInGKE
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
        
      - name: Publish Unit Test Results
        uses: cloudbees-io/publish-test-results@v1
        with:
          test-type: JUnit
          folder-name: src/test

      - uses: cloudbees-io/publish-evidence-item@v1
        name: Publish Evidence
        with:
          content: |-
            # Workflow Evidence
            - **Workflow ID:** ${{ cloudbees.run_id }}
            - **Commit ID and Message:** ${{ steps.commit_info.outputs.commit_info }}
            - **Link to CI Build:** [CI Build Link](https://cloudbees-ci.example.com/${{ cloudbees.run_id }})
            - **Unit Test Results:** Available in JUnit report
            - **Code Coverage:** $(jq '.component.measures[] | select(.metric == "coverage") | .value' /cloudbees/workspace/sonar-results.json)%
            - **Critical Violations:** $(jq '.component.measures[] | select(.metric == "critical_violations") | .value' /cloudbees/workspace/sonar-results.json)
