apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - main
jobs:
  Checkout:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

  Build:
    needs: Checkout
    steps:
      - name: Configure git
        uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      - name: Build
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          mvn clean install

  Evidence:
    needs: Build
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Read JSON file content
        uses: docker://alpine/git:latest
        id: read-json
        run: |
          # Replace 'path/to/yourfile.json' with the actual path to your JSON file
          cat commit.json > json_content.txt

      - name: Set JSON content as environment variable
        uses: docker://alpine/git:latest
        id: set-env
        run: |
          JSON_CONTENT=$(cat json_content.txt)
          echo "JSON_CONTENT<<EOF" >> $GITHUB_ENV
          echo "$JSON_CONTENT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Publish evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |
            - Workflow ID: ${{ cloudbees.run_id }}
            - URL: ${{ cloudbees.api.url }}
            ## JSON File Content
            - JSON Content:
              ```json
              ${{ steps.set-env.outputs.JSON_CONTENT }}
              ```
