apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  Checkout:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      - name: Get Commit Info
        uses: docker://alpine/git:latest
        id: commitinfo
        run: |
          COMMIT_ID=$(git rev-parse HEAD)
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "commit_id=${COMMIT_ID}" >> $CLOUDBEES_OUTPUTS/commit_id
          echo "commit_msg=${COMMIT_MSG}" >> $CLOUDBEES_OUTPUTS/commit_msg
    outputs:
      commit_id: ${{ steps.commitinfo.outputs.commit_id }}
      commit_msg: ${{ steps.commitinfo.outputs.commit_msg }}

  Build:
    needs: Checkout
    steps:
      - name: Configure git
        uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      - name: Build
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          mvn clean install

  UnitTest:
    needs: Build
    outputs:
      unitTestResults: ${{ steps.RunUnitTest.outputs.mvn_test_stdio1 }}
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      - name: RunUnitTest
        id: RunUnitTest
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          mvn test > "$CLOUDBEES_OUTPUTS/mvn_test_stdio"
          cat "$CLOUDBEES_OUTPUTS/mvn_test_stdio" | grep "Tests run:" | tail -1 > "$CLOUDBEES_OUTPUTS/mvn_test_stdio1"

  StaticAnalysis:
    outputs:
     BLOCKER_COUNT: ${{ steps.FetchSonarQubeIssues.outputs.BLOCKER_COUNT }}
     CRITICAL_COUNT: ${{ steps.FetchSonarQubeIssues.outputs.CRITICAL_COUNT }}
     MAJOR_COUNT: ${{ steps.FetchSonarQubeIssues.outputs.MAJOR_COUNT }}
     MINOR_COUNT: ${{ steps.FetchSonarQubeIssues.outputs.MINOR_COUNT }}
    steps:

      - name: Fetch SonarQube Issues
        id: FetchSonarQubeIssues
        uses: docker://alpine/git:latest
        run: |
         apk add --no-cache curl jq
         curl -u ${{ secrets.username }}:${{ secrets.password }} \
         "https://sonarqube.cb-demos.io/api/issues/search?componentKeys=config-server&severities=BLOCKER,CRITICAL,MAJOR" \
         -o sonar-issues.json
         BLOCKER_COUNT=$(jq '[.issues[] | select(.severity=="BLOCKER")] | length' sonar-issues.json)
         CRITICAL_COUNT=$(jq '[.issues[] | select(.severity=="CRITICAL")] | length' sonar-issues.json)
         MAJOR_COUNT=$(jq '[.issues[] | select(.severity=="MAJOR")] | length' sonar-issues.json)
         MINOR_COUNT=$(jq '[.issues[] | select(.severity=="MINOR")] | length' sonar-issues.json)

         echo "BLOCKER_COUNT=${BLOCKER_COUNT}" >> $CLOUDBEES_OUTPUTS/BLOCKER_COUNT
         echo "CRITICAL_COUNT=${CRITICAL_COUNT}" >> $CLOUDBEES_OUTPUTS/CRITICAL_COUNT
         echo "MAJOR_COUNT=${MAJOR_COUNT}" >> $CLOUDBEES_OUTPUTS/MAJOR_COUNT
         echo "MINOR_COUNT=${MINOR_COUNT}" >> $CLOUDBEES_OUTPUTS/MINOR_COUNT


  Evidence:
    needs:
      - UnitTest
      - Checkout
      - StaticAnalysis
    steps:
      - uses: cloudbees-io/publish-evidence-item@v1
        name: Publish evidence
        with:
          content: |
            - Workflow ID: ${{ cloudbees.run_id }}
            - URL: ${{ cloudbees.api.url }}

             ## CommitInfo
            - **Commit ID:** "${{ needs.Checkout.outputs.commit_id }}"
            - **Commit Message:** "${{ needs.Checkout.outputs.commit_msg }}"
            - Unit Test Results: "${{ needs.UnitTest.outputs.unitTestResults }}"

             ## SonarQube Analysis Results

             | Severity  | Issue Count |
             |-----------|-------------|
             | BLOCKER   | ${{ needs.StaticAnalysis.outputs.BLOCKER_COUNT }} |
             | CRITICAL  | ${{ needs.StaticAnalysis.outputs.CRITICAL_COUNT }} |
             | MAJOR     | ${{ needs.StaticAnalysis.outputs.MAJOR_COUNT }} |
             | MINOR     | ${{ needs.StaticAnalysis.outputs.MINOR_COUNT }} |