apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - main
jobs:
  Checkout:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1

  Build:
    needs: Checkout
    services:
      docker:
        image: docker:20.10.9
        privileged: true  # Necessary to run Docker in Docker (DinD)
    steps:
      - uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace

      - name: checkout
        uses: cloudbees-io/checkout@v1

      - name: Build
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          mvn clean install -DskipTests=true

      - name: Build Docker Image
        uses: docker://docker:20.10.9
        run: |
          docker build -t my-app:latest /cloudbees/workspace
  

     
          