apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - main
jobs:
  Checkout:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

  Build:
    needs: Checkout
    steps:
      - name: Configure git
        uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace

      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Build
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          mvn clean install -DskipTests=true

      - name: Configure container registry credentials
        id: dockerconfig
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: ${{ secrets.STAGING_DOCKER_REGISTRY }}
          username: ${{ secrets.STAGING_DOCKER_USERNAME }}
          password: ${{ secrets.STAGING_DOCKER_PASSWORD }}

      - name: Push image to OCI registry
        uses: cloudbees-io/kaniko@v1
        with:
          dockerfile: Dockerfile
          context: .
          destination: ${{ secrets.STAGING_DOCKER_REGISTRY }}/${{ secrets.STAGING_DOCKER_USERNAME }}/configserver:3.2.4
          build-args: docker images

      - name: Create combined deployment and service YAML
        uses: docker://alpine:latest
        run: |
          cat <<EOF > kubeconfig.yaml
          apiVersion: v1
          clusters:
          - cluster:
              certificate-authority-data: ${{ secrets.GCP_SA_KEY }}
          server: https://35.231.169.133
          name: gke_core-flow-research_us-east1-b_preview
          contexts:
          - context:
              cluster: gke_core-flow-research_us-east1-b_preview
              user: gke_core-flow-research_us-east1-b_preview
            name: gke_core-flow-research_us-east1-b_preview
          current-context: gke_core-flow-research_us-east1-b_preview
          kind: Config
          preferences: {}
          users:
          - name: gke_core-flow-research_us-east1-b_preview
            user:
              exec:
                apiVersion: client.authentication.k8s.io/v1beta1
                command: gke-gcloud-auth-plugin
                installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
                  https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-access-for-kubectl#install_plugin
                provideClusterInfo: true
          EOF

      - name: Install gke-gcloud-auth-plugin
        uses: docker://google/cloud-sdk:latest
        run: |
          apt-get update && apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

      - name: Configure Kubernetes CLI
        uses: docker://bitnami/kubectl:latest
        run: |
          mkdir -p ~/.kube
          mv kubeconfig.yaml ~/.kube/config
          kubectl config view

      - name: Deploy to Kubernetes
        uses: docker://bitnami/kubectl:latest
        run: |
          kubectl get nodes











          
          

          
          