apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - main
jobs:
  Checkout:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

  Build:
    needs: Checkout
    steps:
      - name: Configure git
        uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace

      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Build
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          mvn clean install -DskipTests=true

      - name: Configure container registry credentials
        id: dockerconfig
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: ${{ secrets.STAGING_DOCKER_REGISTRY }}
          username: ${{ secrets.STAGING_DOCKER_USERNAME }}
          password: ${{ secrets.STAGING_DOCKER_PASSWORD }}

      - name: Push image to OCI registry
        uses: cloudbees-io/kaniko@v1
        with:
          dockerfile: Dockerfile
          context: .
          destination: ${{ secrets.STAGING_DOCKER_REGISTRY }}/${{ secrets.STAGING_DOCKER_USERNAME }}/configserver:3.2.4
          build-args: docker images
      
  Config:
    needs: Build
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
        
      - name: Install gke-gcloud-auth-plugin
        uses: docker://ubuntu:latest
        run: |
          apt-get update
          apt-get install -y google-cloud-cli-gke-gcloud-auth-plugin
          
      - name: Configure Kubernetes CLI
        uses: docker://bitnami/kubectl:latest
        run: |
          mkdir -p ~/.kube
          mv /cloudbees/workspace/kubeconfig.yaml  ~/.kube/config
          kubectl config view
         
      
      - name: Configure Kubernetes CLI
        uses: docker://bitnami/kubectl:latest
        run: |
           kubectl get nodes   