apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - "**"
jobs:
  Checkout:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1
  Build:
    needs: Checkout
    steps:
      - uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace
      - name: checkout
        uses: cloudbees-io/checkout@v1
      - name: Build
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          mvn clean install -DskipTests=true
  
  Deploy:
    needs: Build
    steps:
      - name: Configure AWS CLI
        uses: docker://amazon/aws-cli:latest
        run: |
          aws configure set aws_access_key_id ASIAT43X4R4GOTGVJTGF
          aws configure set aws_secret_access_key sVFpVWOWtOgw3R9XTZ3Olgfpp8Rz0FdhjRSbSvj+
          aws configure set default.region us-east-1
      - name: Deploy
        uses: docker://amazon/aws-cli:latest
        run: |
          aws ec2 run-instances --image-id ami-04b70fa74e45c3917 --count 1 --instance-type t2.micro --key-name MyKeyPair --security-group-ids sg-0619d58b2e0168607 --region us-east-1
