apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - main
jobs:
  Checkout:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1

  Build:
    needs: Checkout
   
    steps:
      - name: Setup Docker-in-Docker
        uses: docker://docker:20.10.7
        run: |
          dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 &>/dev/null &
          sleep 5  # Wait for Docker to start up
      
          
      - uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace

      - name: checkout
        uses: cloudbees-io/checkout@v1

      - name: Build
        uses: docker://maven:3-eclipse-temurin-17
        run: |
            mvn clean install -DskipTests=true
     
  
      - name: Build Docker image
        uses: docker://docker:20.10.9-dind
        run: |
          apk add --no-cache docker-cli
          dockerd --iptables=false --ip-masq=false --bridge=none &
          sleep 10
          docker build -t my-config:3.2.4 .
          docker info
        privileged: true
         
     
          