apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - main
jobs:
  Checkout:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

  Build:
    needs: Checkout
    steps:
      - name: Configure git
        uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      - name: Build
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          mvn clean install

  StaticAnalysis:
    steps:
      - uses: cloudbees-io/sonarqube-sast-scan-code@v1
        name: Scan
        kind: scan
        with:
          server-url: https://sonarqube.cb-demos.io
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          language: Java
      - uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v2
        name: Scan with Java
        kind: scan
        with:
          language: JAVA
      - uses: cloudbees-io/findsecbugs-sast-scan-code@v1
        name: Scan with Find Security Bugs
        kind: scan
        with:
          language: LANGUAGE_JAVA
      - uses: sbatchelder-cba/sonarqube-cba@v0.0.3
        name: Scan GP
        with:
          project-key: config-server
          token: ${{ secrets.token }}
      - name: Fetch SonarQube Issues
        id: fetch_issues
        uses: docker://alpine/git:latest
        run: |
          apk add --no-cache curl jq

          curl -u ${{ secrets.username }}:${{ secrets.password }} \
          "https://sonarqube.cb-demos.io/api/issues/search?componentKeys=config-server&severities=BLOCKER,CRITICAL,MAJOR" \
          -o sonar-issues.json

          BLOCKER_COUNT=$(jq '[.issues[] | select(.severity=="BLOCKER")] | length' sonar-issues.json)
          CRITICAL_COUNT=$(jq '[.issues[] | select(.severity=="CRITICAL")] | length' sonar-issues.json)
          MAJOR_COUNT=$(jq '[.issues[] | select(.severity=="MAJOR")] | length' sonar-issues.json)

          echo "BLOCKER_COUNT=$BLOCKER_COUNT" >> $GITHUB_ENV
          echo "CRITICAL_COUNT=$CRITICAL_COUNT" >> $GITHUB_ENV
          echo "MAJOR_COUNT=$MAJOR_COUNT" >> $GITHUB_ENV

  Evidence:
    needs: StaticAnalysis
    steps:
      - name: Print issue counts
        uses: docker://alpine/git:latest
        run: |
          echo "BLOCKER_COUNT=${{ env.BLOCKER_COUNT }}"
          echo "CRITICAL_COUNT=${{ env.CRITICAL_COUNT }}"
          echo "MAJOR_COUNT=${{ env.MAJOR_COUNT }}"

      - name: Publish evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |
            - Workflow ID: ${{ cloudbees.run_id }}
            - URL: ${{ cloudbees.api.url }}
            - Issue Summary:
              | Severity | Count |
              |----------|-------|
              | Blocker  | ${{ env.BLOCKER_COUNT }} |
              | Critical | ${{ env.CRITICAL_COUNT }} |
              | Major    | ${{ env.MAJOR_COUNT }} |