apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - main
jobs:
  Checkout:
    steps:
       - name: Checkout Code
         uses: actions/checkout@v2
    
       - name: Fetch commit-info.md content
         id: fetch_content
         uses: docker://alpine/git:latest
         run: |
          curl -s https://github.com/cashokannamalai/spring-petclinic-config-server/blob/main/commit-info.md -o commit-info.md
          content=$(cat commit-info.md)
          echo "::set-output name=file_content::$content"
    
       - name: Publish evidence
         uses: cloudbees-io/publish-evidence-item@v1
         with:
          content: |
            - Workflow ID: ${{ github.run_id }}
            - URL: ${{ github.event.repository.html_url }}/commit-info.md
            - File Content: |
              ${{ steps.fetch_content.outputs.file_content }}