apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - main

jobs:
  Checkout:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

  Build:
    needs: Checkout
    steps:
      - name: Configure git
        uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace
      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Capture Commit Information
        uses: docker://alpine:latest
        run: |
          echo "COMMIT_ID=$(git rev-parse HEAD)" > commit_info.txt
          echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> commit_info.txt

      - name: Build
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          mvn clean install
        # Ensure commit_info.txt is available in the workspace or artifact
        # This depends on how CloudBees handles workspace artifacts

  Evidence:
    needs: Build
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Read Commit Information
        uses: docker://alpine:latest
        run: |
          COMMIT_ID=$(grep 'COMMIT_ID=' commit_info.txt | cut -d'=' -f2)
          COMMIT_MESSAGE=$(grep 'COMMIT_MESSAGE=' commit_info.txt | cut -d'=' -f2)
          echo "COMMIT_ID=$COMMIT_ID" >> $GITHUB_ENV
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV

      - name: Publish workflow evidence item
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |-
            ## Workflow Evidence
            | Property      | Value                                         |
            |---------------|-----------------------------------------------|
            | Commit ID     | ${env.COMMIT_ID}                             |
            | Commit Message| ${env.COMMIT_MESSAGE}                        |
          format: MARKDOWN
