apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - main
jobs:
  Checkout:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

  Build:
    needs: Checkout
    outputs:
      CommitIdFile: ${{ steps.get_commit_id.outputs.CommitIdFile }}
    steps:
      - name: Configure git
        uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      - name: Get Commit ID
        id: get_commit_id
        uses: docker://alpine/git:latest
        run: |
          echo "Commit ID: $(git rev-parse HEAD)" > commit_id.txt
          echo "::set-output name=CommitIdFile::$(cat commit_id.txt)"
      - name: Build
        uses: docker://maven:3-eclipse-temurin-17
        id: build
        run: |
          mvn clean install

      - name: Publish Evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |
            - Workflow ID: ${{ cloudbees.run_id }}
            - URL: ${{ cloudbees.api.url }}
            - Commit ID: ${{ steps.get_commit_id.outputs.CommitIdFile }}
