apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - main
jobs:
  Checkout:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1

  Build:
    needs: Checkout
    steps:
      - name: Mount Docker Socket
        uses: docker://alpine/git:latest
        run: |
          apk add --no-cache docker
          docker --version  # Verify Docker client is installed
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket

      - uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace
      - name: checkout
        uses: cloudbees-io/checkout@v1
      - name: Build
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          mvn clean install -DskipTests=true

  BuildDockerImage:
    needs: Build
    steps:
      

      - name: Build Docker image
        uses: docker://docker:23.0.1
        run: |
          docker build -t configimage:3.2.4 .