apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - main

jobs:
  Checkout:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

  Build:
    needs: Checkout
    steps:
      - name: Configure git
        uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      
      - name: Build
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          mvn clean install

  Evidence:
   needs: Build
   steps:
    - name: Checkout
      uses: cloudbees-io/checkout@v1

    - name: Get commit information
      uses: docker://alpine/git:latest
      id: get_commit_info
      run: |
        COMMIT_ID=$(git rev-parse HEAD)
        echo "${COMMIT_ID}" > commit_id.txt

    - name: Read commit ID
      id: read_commit_id
      uses: docker://alpine/git:latest
      run: |
        COMMIT_ID=$(cat commit_id.txt)
        echo "COMMIT_ID=${COMMIT_ID}" >> $GITHUB_ENV

    - name: Debug Variables
      uses: docker://alpine/git:latest
      run: |
        echo "Run ID: ${{ cloudbees.run_id }}"
        echo "API URL: ${{ cloudbees.api.url }}"
        echo "Commit ID: ${{ env.COMMIT_ID }}"

    - name: Publish evidence
      uses: cloudbees-io/publish-evidence-item@v1
      with:
        content: |
          - Workflow ID: ${{ cloudbees.run_id }}
          - URL: ${{ cloudbees.api.url }}
          - Commit ID: ${{ env.COMMIT_ID }}
