apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - main
jobs:
  Checkout:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1

  Build:
    needs: Checkout
   
    steps:
      - name: Install Docker
        uses: docker://alpine:latest 
        run: |
          apk add --update docker
          service docker start || true 
          docker --version  
          docker info 

      - name: Wait for Docker to Start
        uses: docker://alpine:latest 
        run: |
          timeout 15s sh -c "until docker info; do echo Waiting for Docker to start...; sleep 1; done" 
      - uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace

      - name: checkout
        uses: cloudbees-io/checkout@v1
      - name: Build
        uses: docker://maven:3-eclipse-temurin-17
        run: |
            mvn clean install -DskipTests=true
            
     
  
    
          