apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - main
jobs:
  Checkout:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

  Build:
    needs: Checkout
    steps:
      - name: Configure git
        uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace
      - name: Checkout
        uses: cloudbees-io/checkout@v1
        
      - name: Get Commit Information
        uses: docker://alpine/git:latest
        run: |
           echo "Commit ID: $(git rev-parse HEAD)" > /cloudbees/workspace/commit-info.txt
           echo "Commit Message: $(git log -1 --pretty=format:%s)" >> /cloudbees/workspace/commit-info.txt

      - name: Build
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          mvn clean install
 
      - name: Publish Build Evidence
        uses: ./.github/actions/publish-evidence-item
        with:
          content: |
            Commit ID: $(git rev-parse HEAD)
            Commit Message: $(git log -1 --pretty=format:%s)
            Build Status: Success
          format: MARKDOWN

  Evidence:
    needs: Build
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
        
      - name: Get Commit Information
        uses: docker://alpine/git:latest
        run: |
           echo "Commit ID: $(git rev-parse HEAD)" > /cloudbees/workspace/commit-info.txt
           echo "Commit Message: $(git log -1 --pretty=format:%s)" >> /cloudbees/workspace/commit-info.txt

      - name: Publish test results
        uses: cloudbees-io/publish-test-results@v1
        with:
          test-type: JUnit
          folder-name: src/test
