apiVersion: cashokannamalai/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    steps:
      
      - name: Set up Google Cloud CLI
        uses: cashokannamalai/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true