apiVersion: tekton.dev/v1beta1
kind: Pipeline
name: My workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    steps:
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
