apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My Workflow with Approval
on:
  pull_request:
    branches:
      - "**"
jobs:
  approval:
    environment: ashok
    steps:
      - name: Request Approval
        uses: docker://alpine/git:latest
        run: |
          echo "Waiting for approval..."
         
          APPROVAL_STATUS="approved"  
      - name: Check Approval Status
        uses: docker://alpine/git:latest
        run: |
          if [ "$APPROVAL_STATUS" != "approved" ]; then
            echo "Pull request was rejected. Exiting."
            exit 1 
          else
            echo "Pull request approved. Proceeding with the build."
          fi

  build:
    needs: approval  # This job depends on the approval job
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
